server.port=8080
spring.application.name=BankingApp

# Conexiunea la PostgreSQL din Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/eBank
spring.datasource.username=postgres
spring.datasource.password=postgre_sql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# Setare pentru generarea tabelelor
spring.jpa.hibernate.ddl-auto=update

# Optional: Afiseaza in consola ce cod SQL executa Spring in spate
spring.jpa.show-sql=true